name: mind_wave
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  bubble: ^1.2.1
  cloud_firestore: ^5.6.7
  filter_list: ^1.0.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  rename_app: ^1.6.3
  change_app_package_name: ^1.5.0
  icons_launcher: ^3.0.1

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/chat.jpeg
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/google_button.png
